version: '3'
services:
  api:
    build: ./api
    container_name: api
    restart: always
    ports:
      - 9000:9000
    env_file: ./api/.env
  web:
    build: ./web
    container_name: web
    restart: always
    ports:
      - 80:8080
    links:
      - api

